version: "3.9"

services:
  db:
    image: postgres
    container_name: db
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=tracker
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - ./db/shortcut/data:/var/lib/postgresql/data
    ports:
      - "5435:5432"
    restart: always

  job4j_url_shortcut:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/url_shortcut
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    container_name: job4j_url_shortcut
    ports:
      - "127.0.0.1:8080:8080"
    depends_on:
      - db


